In [1]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np . array ([ 1 , 2 , 3 ])

# Create a vector as a column
vector_column = np . array ([[ 1 ],
                             [ 2 ],
                             [ 3 ]])

In [2]:
vector_column

array([[1],
       [2],
       [3]])

In [3]:
# Load library
import numpy as np

# Create a matrix
matrix = np . array ([[ 1 , 2 ],
                      [ 1 , 2 ],
                      [ 1 , 2 ]])

In [4]:
type(matrix)

numpy.ndarray

In [7]:
# Load library
import numpy as np

# Create a matrix
matrix = np . array ([[ 1 , 2 ],
                      [ 1 , 2 ],
                      [ 1 , 2 ]])

In [8]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [17]:
matrix_object = np . asmatrix ([[ 1 , 2 ],
                                [ 1 , 2 ],
                                [ 1 , 2 ]])


In [15]:
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [11]:
# Load libraries
import numpy as np

from scipy import sparse

# Create a matrix
matrix = np . array ([[ 0 , 0 ],
                      [ 0 , 1 ],
                      [ 3 , 0 ]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse . csr_matrix ( matrix )

In [12]:
matrix_sparse

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>

In [8]:
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [ ]:
matrix_large = np . array ([[ 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ],
                            [ 0 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ],
                            [ 3 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse . csr_matrix ( matrix_large )
# View original sparse matrix
print ( matrix_sparse )
 
# View larger sparse matrix
print ( matrix_large_sparse )
 

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
